// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  accent: string;
  accentForeground: string;
  activeColor: string;
  background: string;
  borderColor: string;
  card: string;
  cardForeground: string;
  colorStockGreen: string;
  colorStockRed: string;
  destructive: string;
  destructiveForeground: string;
  foreground: string;
  gray: string;
  input: string;
  muted: string;
  mutedForeground: string;
  popover: string;
  popoverForeground: string;
  primary: string;
  primaryForeground: string;
  radius: string;
  ring: string;
  secondary: string;
  secondaryForeground: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
}
declare const cssExports: CssExports;
export default cssExports;
